- name: Check SSH status
  systemd:
    name: "{{ 'ssh' if ansible_facts['os_family'] == 'Debian' else 'sshd' }}"
  register: srv

- name: Debug
  debug:
    var: srv.status.ActiveState

- name: Check if SSH port is open in UFW
  wait_for:
    port: 22
    timeout: 5
  notify: SSHisOpen

- name: Check Apache status
  systemd:
    name: "{{ 'apache2' if ansible_facts['os_family'] == 'Debian' else 'httpd' }}"
  register: app

- name: Debug
  debug:
    var: app.status.ActiveState

- name: Check if HTTP port is open in UFW
  wait_for:
    port: 80
    timeout: 5
  notify: HTTPisOpen
