- hosts: webserver
  become: true

  tasks:
    - name: Install UFW
      ansible.builtin.package:
        name: ufw
        state: present

    - name: Enabling UFW
      community.general.ufw:
        state: enabled

    - name: Allow ssh
      community.general.ufw:
        rule: allow
        port: 22

    - name: Allow http
      community.general.ufw:
        rule: allow
        port: 80
