- hosts: webserver
  become: true
  tasks:
    - name: "Installer Apache sur Debian OS"
      apt:
        name: apache2
        state: present
      when: ansible_facts["os_family"] == 'Debian'
    - name: "Démarrer le service Apache"
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_facts["os_family"] == 'Debian'

    - name: "Installer httpd sur RedHat OS"
      dnf:
        name: httpd
        state: present
      when: ansible_facts["os_family"] == 'RedHat'
    - name: "Démarrer le service httpd"
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_facts["os_family"] == 'RedHat'
