- name: Install Apache
  ansible.builtin.package:
    name: "{{ apache_pkg }}"
    state: present

- name: Enable Apache service
  ansible.builtin.service:
    name: "{{ apache_pkg }}"
    state: started
    enabled: yes
