- name: Add a sudo user
  user:
    name: "{{ user }}"
    password: "{{ pwd }}"
    groups: "{{ group[ansible_facts['os_family']] }}"
    append: yes
    state: present
  when: access  == 'y'

- name: Add a user
  user:
    name: "{{ user }}"
    password: "{{ pwd }}"
    state: present
  when: access == 'n'
