- hosts: webserver
  become: true

  vars:
    group:
      Debian: sudo
      RedHat: wheel

  vars_prompt:
    - name: user
      prompt: Username

    - name: pwd
      prompt: Password

    - name: access
      prompt: Is it a sudo user?

  tasks:
    - name: Add a sudo user
      user:
        name: "{{ user }}"
        password: "{{ pwd | password_hash('sha512') }}"
        groups: "{{ group[ansible_facts['os_family']] }}"
        append: yes
        state: present
      when: " access  == 'yes' or  access  == 'y' "

    - name: Add a user
      user:
        name: "{{ user }}"
        password: "{{ pwd | password_hash('sha512') }}"
        state: present
      when: " access == 'no' or access == 'n' "
